# MEV Arbitrage Bot Test Configuration
# This configuration is for connecting to a local Hardhat testnet

# Ethereum network configuration
[ethereum]
rpc_url = "http://localhost:8545"
ws_url = "ws://localhost:8545"
chain_id = 31337  # Hardhat local network
wallet_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"  # Default Hardhat account #0
max_block_lookback = 10
ws_timeout_seconds = 30

# MEV-Share configuration (disabled for local testing)
[mev_share]
api_url = "https://mev-share.flashbots.net"
enabled = false
max_validator_tip = 2  # 2 gwei

# Flash loan configuration
[flash_loan]
# This will be updated with the actual address after deployment
aave_lending_pool = "0x0000000000000000000000000000000000000002"
max_borrow_amount = 100.0  # 100 ETH

# Token configurations (will be updated after deployment)
[[flash_loan.tokens]]
symbol = "WETH"
address = "0x0000000000000000000000000000000000000006"
decimals = 18

[[flash_loan.tokens]]
symbol = "USDC"
address = "0x0000000000000000000000000000000000000007"
decimals = 6

[[flash_loan.tokens]]
symbol = "DAI"
address = "0x0000000000000000000000000000000000000008"
decimals = 18

# DEX configurations (will be updated after deployment)
[dex.uniswap]
enabled = true
factory_address = "0x0000000000000000000000000000000000000000"
router_address = "0x0000000000000000000000000000000000000003"
pools = []  # Will be populated automatically

[dex.sushiswap]
enabled = true
factory_address = "0x0000000000000000000000000000000000000000"
router_address = "0x0000000000000000000000000000000000000004"
pools = []  # Will be populated automatically

[dex.curve]
enabled = true
factory_address = "0x0000000000000000000000000000000000000000"
router_address = "0x0000000000000000000000000000000000000005"
pools = []  # Will be populated automatically

# Arbitrage configuration
[arbitrage]
min_profit_threshold = 0.01  # $0.01 for testing
max_hops = 3
slippage_tolerance = 0.5  # 0.5%
evaluation_timeout_ms = 500
max_concurrent_evaluations = 5

# Adding the missing contract configuration
[arbitrage.contract]
contract_address = "0x0000000000000000000000000000000000000001"  # ArbitrageExecutor address
deploy_if_missing = false
deployment_gas_limit = 5000000

# Gas price configuration
[gas]
strategy = "fixed"  # Use fixed gas price for local testnet
max_gas_price = 10  # 10 gwei
base_fee_multiplier = 1.0
priority_fee = 1  # 1 gwei
gas_limit = 500000

# Security configuration
[security]
transaction_timeout = 60  # 60 seconds
min_price_sources = 1  # Only 1 for testing
max_price_deviation = 5.0  # 5% for testing
simulate_transactions = true
max_execution_slippage = 2.0  # 2% for testing